### ISSUE TITLE
[Webview][QML] Native settings menu

### ISSUE THREAD

**Issue by pherjung** [hydrogen-sailfishos/sfos-hydrogen#18]

**Comment by pherjung** [comment]
This feature adds a scrolling bug. Bug that is not present on the jolla-email with this [patch](https://openrepos.net/content/markkyboy/patch-returns-pulley-menu-email-view)

**Comment by pherjung** [comment]
Asked on the next [community-meeting](https://forum.sailfishos.org/t/community-meeting-on-irc-23rd-november-2023/17342/3). Hopefully, we'll get an answer.

**Comment by pherjung** [comment]
I agree. I enable a check to disable the pulley menu when the user is in the settings menu. I'll add another check.

You have added some pages for the pulley menu, on which branch are they?

**Comment by pherjung** [comment]
> You have added some pages for the pulley menu, on which branch are they?

Oh, already merged. Nice!
I need to find out a way to only disable Hydrogen settings. I may have an idea.

**Comment by b100dian** [comment]
Alternatively, we coikd have the pulkey menu only on the settings page and if we detect a "modal" dkalog, to present a Back option, just in case

**Comment by b100dian** [comment]
Closing this one in favor of https://github.com/hydrogen-sailfishos/sfos-hydrogen/issues/42
