### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by thigg** [hydrogen-sailfishos/sfos-hydrogen#3]
Enable push notifications in hydrogen and send them over to sailfishos

**Comment by thigg** [comment]
Maybe wait until new browser version is released

**Comment by b100dian** [comment]
This is currently done through [polling the IndexedDB](https://github.com/hydrogen-sailfishos/sfos-hydrogen/blob/master/qml/notificationCount.js#L50) then surfacing their count change as a notification.
True browser notifications from the worker are not yet available in sailfishos-browser and webview.
We'll re-open a new issue when support is present.
