### ISSUE TITLE
Chum issues

### ISSUE THREAD

**Issue by rinigus** [hydrogen-sailfishos/sfos-hydrogen#33]
There are few issues in Chum:

- in SPEC, I would suggest to fix URL. Right now it points to https://github.com/harbour-sailfishos/sfos-hydrogen . With URL fixed, Chum GUI would be able to show opened issues, releases and other info

- is there a reason a file "release-sfos-0.4.1.zip" is bundled? All should be possible to pull via _service, or do I miss something?

- more serious issue preventing the build is "have choice for libKF5Archive.so.5()(64bit) needed by nemo-qml-plugin-filemanager: libKF5Archive5 libkf5archive". This looks to be caused by https://build.sailfishos.org/package/show/sailfishos:chum:testing/karchive - @piggz, does it interfere with SFOS provided package? In this case we should probably disable export of symbols or make one of them preferred one on repo level.

**Comment by piggz** [comment]
Yeah, ive seen the karchive issue before but never got around to fixing.... i imported karchive many years ago for amazfish, though i cant be sure which package came first, mine of Jollas .... in any case, maybe I should investigate using the jolla version and drop the one from chum

**Comment by b100dian** [comment]
Sorry I'm late seeing this.
For the artifact part I asked [this](https://forum.sailfishos.org/t/community-meeting-on-irc-7th-december-2023/17429/4) maybe tar_git could use the fileserver URL.
For the project URL: Thanks **nephros** for fixing it.
For the libKF5Archive error, thanks **piggz** for fixing it!

**Comment by b100dian** [comment]
Just a note about the artifact:
@rinigus this is the app I initially built nodejs on OBS for. To make the npm/yarn build run without network connection, it required a 200+MiB yarn.cache file as seen [here](https://build.sailfishos.org/package/show/home:b100dian:hydrogen/harbour-hydrogen).
Having the build partially on github and using _that_ output as a 5MiB artifact is no-brainer compared to that.

**Comment by rinigus** [comment]
Sounds reasonable to me. We have to make exceptions for a good cause and I think it is a great example of it.

**Comment by b100dian** [comment]
> Sounds reasonable to me. We have to make exceptions for a good cause and I think it is a great example of it.

Thank you!

**Comment by b100dian** [comment]
This is slightly improved by using an actual URL of the artifact as shown [here](https://github.com/hydrogen-sailfishos/sfos-hydrogen/compare/test/download_files?expand=1) and adding `<service name="download_files"/>` after `tar_git` in [_service](https://build.sailfishos.org/package/view_file/home:b100dian:sfos-hydrogen/harbour-hydrogen/_service?expand=1).
Ideally, something like this [node modules](https://github.com/openSUSE/obs-service-node_modules) `_service` would work better.

**Comment by b100dian** [comment]
Also, the node_modules service is not directly usable for yarn, as yarn has its own yaml lockfile and needs conversion to package-lock.json such as https://github.com/imsnif/synp.
I am closing this for now, but please re-open if any other ideas come aboard..
